In [1]:
import numpy as np
np.__version__

'1.20.1'

In [2]:
list1 = [1,2,3,4,5]
type(list1)

list

In [3]:
arr1 = np.array(list1)
type(arr1)

numpy.ndarray

In [4]:
list2 = [10,11,12,13]
arr2=np.array(list2)
arr2

array([10, 11, 12, 13])

In [6]:
list1+list2

[1, 2, 3, 4, 5, 10, 11, 12, 13]

In [ ]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [9]:
arr3 =np.array([10,11,12,13,14])
arr1 + arr3

array([11, 13, 15, 17, 19])

In [10]:
mat1 = np.random.randint(1,10,(3,4))
mat1

array([[1, 7, 3, 8],
       [2, 6, 9, 2],
       [4, 8, 2, 4]])

In [11]:
mat1.shape

(3, 4)

In [12]:
mat1.dtype

dtype('int32')

In [14]:
mat2 = np.random.randint(1,10,(5,6), dtype = np.int16)
mat2

array([[6, 5, 8, 1, 1, 7],
       [2, 5, 4, 1, 3, 5],
       [9, 9, 8, 7, 5, 6],
       [4, 9, 2, 5, 2, 3],
       [6, 3, 8, 7, 6, 1]], dtype=int16)

In [15]:
mat2.size

30

In [16]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1=np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
arr1=np.arange(10,20,2)
arr1

array([10, 12, 14, 16, 18])

In [21]:
arr2=np.random.randint(10,20,15)
arr2

array([17, 16, 16, 15, 17, 15, 17, 10, 19, 15, 18, 14, 10, 12, 17])

In [22]:
arr2=np.random.randint(10,20,15).reshape(5,3)
arr2

array([[17, 10, 10],
       [15, 13, 13],
       [18, 19, 10],
       [16, 17, 19],
       [17, 13, 15]])

In [23]:
mat1=np.random.randint(10,20,(3,4))
mat1

array([[19, 12, 11, 10],
       [18, 19, 18, 17],
       [16, 11, 14, 13]])

In [25]:
mat2=np.random.randint(10,20,4)
mat2

array([14, 11, 10, 15])

In [26]:
mat1+mat2

array([[33, 23, 21, 25],
       [32, 30, 28, 32],
       [30, 22, 24, 28]])

In [27]:
mat3=np.random.randint(10,20,2)
mat3

array([19, 13])